-- Run AFTER schema.sql. The PERSISTENT template library Claude reads from.
-- 'Save to library' in the app writes here; one-off tasks stay only on their event.
create table if not exists library_tasks (
  id uuid primary key default gen_random_uuid(),
  workstream text not null,        -- workstream / activation it belongs to
  timing text,
  title text not null,
  owner text,
  applies_to text,
  notes text,
  created_at timestamptz default now(),
  unique (workstream, title)
);
alter table library_tasks disable row level security;   -- prototype only

-- Seed the library with the current 858 template (so it starts full).
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Create initial project plan','Fern','All events','Fern leads creation. Christina takes over execution ~1 month out.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Register on-site team for event','Christina','All events','Register all team members via Notion. Send confirmations + notify Fern.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Hotel bookings for on-site team','Team','All events','Fern, Christina, or individuals book per Informa partnership terms.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Client kick-off email','Nic','All events','Overview of what to expect, key links, initial client to-dos.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Create internal tracker hub','Christina','All events','') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Event internal kick-off call','Fern + Christina','All events','Internal team kick-off to align on project plan, ownership, and timeline.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Project kickoff','~2 months out','Create overall event deck','Christina','All events','Overall event deck covering key details, agenda, and team roles.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Send top 20 target request + attendee list','Nic','All events','Google Sheet with full event attendee list. Clients check off 20 top targets to invite.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Create client external spreadsheets with attendee lists','Christina','All events','External-facing Google Sheets with attendee lists shared directly with each client.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Send invites to nominated top targets','Chris','All events','Chris sends invites once each client returns their top 20 list.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Collect client to-dos','Christina','All events','Logo, company bio, attendee registrations, calls scheduled.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Client prep call','Nic','All events','~2 weeks out. Nic walks through full prep deck — logistics, expectations, event overview.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Client deal strategy call','JG','All events','JG strategizes with client on talking points, target approach, and event goals.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Confirm GRIP preference designator per partner','Nic','GRIP Meetings','Each partner assigns one person (designator) who will log into GRIP and make meeting selections on behalf of the company.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Operator preference selections open — choose top 40','Nic','GRIP Meetings','Designator receives email with instructions and logs into GRIP to select up to 40 operators they want to meet with.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Review who''s interested — refine operator preferences','Nic','GRIP Meetings','Mid-window check: review mutual interest signals in GRIP and adjust selections before the final deadline. Note: this often falls in a holiday week.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','Final deadline — select operator preferences','Nic','GRIP Meetings','Hard cutoff for all partner preference selections in GRIP. After this, Informa builds the schedule.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — client workstreams','4–6 weeks out','View preliminary meeting schedule + flag issues','Nic','GRIP Meetings','Informa publishes a draft schedule. Review each client''s 10 meetings and flag any conflicts or mismatches directly with Informa.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Build master attendee list','Christina','All events','LinkedIn headshots, brand, job title, buyer intent. Updated multiple times/week.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Map buyer intents to clients','Christina','All events','Match each operator''s top 3 tech priorities to relevant client solutions.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Create internal dossier','Christina','All events','Internal-facing dossier for the 858 team — separate from client dossiers.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Build per-client dossier in Notion','Christina','All events','Agenda, attendee table, buyer intents, map, team/client headshots. One per client.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Add finalized GRIP schedule to client dossier','Christina','GRIP Meetings','Once Informa publishes the preliminary schedule, add each client''s confirmed 10 meetings into their Notion dossier so they can research and prep.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Run prioritization exercise with clients','Christina','All events','Clients nominate: 5 tier 1 targets, 5 tier 2, 10 current customers, 20 detractors.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — dossiers','3–4 weeks out','Publish dossier + create Rebrandly link','Christina','All events','Make Notion page public. Rename link in Rebrandly. Share with client.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — seating & room assignments','1–2 weeks out','Table / room assignments (JG)','JG','Luncheon / Bird circles','JG uses top targets, current customers, detractors + capacity. May review on deal strategy call.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — seating & room assignments','1–2 weeks out','Add assignments to dossiers','Christina','Luncheon / Bird circles','Once JG finalizes, Christina adds table/room assignments to each client''s dossier.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — seating & room assignments','1–2 weeks out','Build ESM trackers','Christina','All events','Shows each client''s tier 1/2 targets + table/room overlap and GRIP meeting schedule. Sent to Nic for onsite ESM use.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — program guide & comms','1–2 weeks out','Draft program guide content','Fern','All events','Fern runs first draft through Claude. Sends to JG + Marty for review and visual direction.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — program guide & comms','1–2 weeks out','Build program guide in Figma','Christina','All events','Christina builds from template. Check-ins with JG + Marty. Export as PDF.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — program guide & comms','1–2 weeks out','Program guide / KBYG send','Chris + JG','All events','JG links PDF. Sent 2–3 days before event to all operators + clients.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — program guide & comms','1–2 weeks out','Stage table / room linking emails','Chris','Luncheon / Bird circles','Chris stages with placeholder photos + LinkedIn links so JG can preview format.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — photography brief','~1 week out','Sign photographer contract','Fern + Christina','All events','Vet and sign per city. Contract, hourly quote. Pre-event call if first time.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — photography brief','~1 week out','Send photography dossier + run of show','Christina','All events','Due dates, shot list, run of show, full attendee headshots, contact info, maps.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — photography brief','~1 week out','Brief Robin (photo organizer)','Christina','All events','Same dossier as photographer. Note when full gallery will be available — that''s his start date.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Venue contract','Fern','Luncheon / Bird circles / 858 House','Fern handles all venue contracts and coordination.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Secure floorplan + AV details','Fern','Luncheon','Get floor plan, room setup, and AV sorted with the venue for the luncheon space.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Food & beverage + espresso cart','Fern','All events','Menu, vendors, contracts. Always include espresso cart. Source beans from a client if possible.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Furniture order','Fern','Luncheon / Bird circles / 858 House','Only if bringing furniture from outside the venue.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Hire staff / extra staffing','Fern','All events','Check-in help, room flips. Especially needed for large-scale events.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Swag for attendees','Fern','All events','Order and coordinate attendee swag — source, brand, and deliver to venue.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Moderator logistics','Fern + Christina','Bird circles','Coordinate moderator details for bird circles: travel, briefing, run of show.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Write opening remarks','JG','Luncheon','JG''s remarks drafted ahead of the luncheon. Multiple check-in rounds before final.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Finalize list of client attendees','Christina','All events','Separate from building the dossier — confirm final client-side attendee list.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Designs & signage','Fern + Christina','All events','Christina designs (badges, note cards, collateral). Fern approves and orders.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','Marketing materials','Christina','All events','Client logos, bios, 858 logo/bio — collect and send to event as needed.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Pre-event — vendors & logistics','Varies','858 House setup coordination','Fern','858 House','Full bar, sushi, carving station, bra bar, check-in system, table reservation setup.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Onsite','Day of event','Final seat assignments (post check-in)','JG','Luncheon / Bird circles','Input final check-in data (no-shows, walk-ins) into Claude project. Reassign if needed.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Onsite','Day of event','858 House check-in + table management','Christina','858 House','Manage full check-in, table reservations, and room flow throughout the event.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Onsite','Day of event','ESM introductions tracking','Nic','All events','Nic + ESMs use trackers to ensure each client meets their tier 1/2 targets.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Onsite','Day of event','GRIP meeting support + ESM coverage','Nic','GRIP Meetings','ESMs ensure each client is at their GRIP meetings on time and equipped. 10 x 10-min back-to-back 1:1s — fast-paced, needs active support.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Onsite','Day of event','Request same-day photo drop','Christina','All events','20–40 edited photos by end of day or early next morning. Must include table/room linking shots.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — table & room linking emails','Within 48 hours','Finalize attendee list by actual table / room','Chris','Luncheon / Bird circles','Chris organizes final list around confirmed seating (no-shows removed).') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — table & room linking emails','Within 48 hours','Organize same-day photos for Chris','Christina','Luncheon / Bird circles','Christina labels and drops photos into Google Drive, linked by table/room.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — table & room linking emails','Within 48 hours','Final review + send linking emails','Chris + JG','Luncheon / Bird circles','One email per table or room. Chris populates, JG final review, send within 48hrs.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — recap','~1 week out','Draft post-event recap using Claude','Christina','All events','Uses program guide, emails, event notes. Covers activations, attendance, speakers, spotlights.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — recap','~1 week out','Nic adds reporting + feedback layer','Nic','All events','Buyer intent reporting, operator/client feedback, ESM debrief notes.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — recap','~1 week out','JG + Marty final content review','JG + Marty','All events','Final edit and approval before Webflow build.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — recap','~1 week out','Build visual recap in Webflow','Christina','All events','Once full gallery is available. Christina builds, JG + Marty review, then make live.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — recap','~1 week out','Send live recap link to Chris','Christina','All events','Chris includes the recap link in all one-on-one follow-up emails.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — photography & Robin','3–10 days out','Receive full photo gallery','Christina','All events','Per contract (3–7 business days). Speakers, food/decor, venue, candids, team, linking photos.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — photography & Robin','3–10 days out','Send gallery + updated attendee list to Robin','Christina','All events','Include any walk-in headshots researched. Updated dossier included for reference.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — photography & Robin','3–10 days out','Confirm Robin delivery + send to Chris','Christina','All events','Robin delivers organized folders (~2–4 days). Christina confirms and forwards to Chris.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — photography & Robin','3–10 days out','Approve Robin''s invoice','Christina','All events','Christina + Chris approve. Notify Fern to process payment.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — one-on-one follow-up','~2 weeks out','Open 1:1 follow-up copy doc','Christina','All events','Christina creates structure + optional Claude template. JG + Chris own the copy.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — one-on-one follow-up','~2 weeks out','Write personalized 1:1 copy','Chris + JG','All events','JG + Chris write personalized follow-ups per operator. Includes event recap and personal note.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — one-on-one follow-up','~2 weeks out','Deliver Robin''s organized photos to Chris','Christina','All events','Once Robin is done. Christina sends organized folder to Chris for photo attachment.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — one-on-one follow-up','~2 weeks out','Final review + send 1:1 emails','Chris + JG','All events','Chris confirms photos + copy. Sends individually with photo + post-event recap link.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — debrief','1–2 weeks out','Client debrief calls','Nic','All events','Nic hosts per client — what worked, what to improve, overall satisfaction.') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — debrief','1–2 weeks out','Log connections in Attio','Christina','All events','Log all new connections and introductions made at the event into Attio (CRM).') on conflict (workstream,title) do nothing;
insert into library_tasks (workstream,timing,title,owner,applies_to,notes) values ('Post-event — debrief','1–2 weeks out','Project wrap-up + template update','Fern + Christina','All events','Close out project plan. Document lessons learned. Update templates for next event.') on conflict (workstream,title) do nothing;
